/**
 * WORLD MODEL — NODES
 *
 * Every node is something that can move, and whose movement has consequences
 * elsewhere. Nodes are deliberately *not* news stories: news is transient, the
 * transmission structure is not. Stories attach to nodes; nodes persist.
 *
 *   kind    macro | rate | inflation | policy | commodity | fx | market |
 *           sector | industry | tech | structural | risk
 *   group   the shelf it sits on in the graph view
 *   blurb   one honest sentence: what this actually measures
 *   proxies tickers/series a reader can follow. Identifiers, not price claims.
 */

const n = (id, label, kind, group, blurb, extra = {}) => ({
  id, label, kind, group, blurb, ...extra,
});

export const NODES = [
  /* --- Monetary policy and rates ---------------------------------------- */
  n("policy_rate", "Fed Policy Rate", "policy", "Monetary",
    "The overnight rate the Federal Reserve targets; the anchor for the whole US curve.",
    { concept: "monetary-policy", proxies: ["FEDFUNDS", "DFEDTARU"] }),
  n("boc_rate", "Bank of Canada Rate", "policy", "Monetary",
    "Canada's overnight policy target, set independently but rarely far from the Fed for long.",
    { proxies: ["V39079"] }),
  n("ecb_rate", "ECB Deposit Rate", "policy", "Monetary",
    "The rate the ECB pays on bank deposits — the effective floor for euro money markets."),
  n("balance_sheet", "Central Bank Balance Sheet", "policy", "Monetary",
    "Quantitative easing expands it and quantitative tightening shrinks it; it moves duration and reserves, not the policy rate.",
    { concept: "quantitative-easing" }),
  n("real_rate", "Real Interest Rate", "rate", "Monetary",
    "The nominal rate minus expected inflation — the number that actually governs investment decisions.",
    { concept: "real-vs-nominal" }),
  n("ust2y", "2-Year Treasury Yield", "rate", "Rates",
    "Mostly a forecast of average policy rates over two years; the market's view of the Fed.",
    { proxies: ["DGS2"] }),
  n("ust10y", "10-Year Treasury Yield", "rate", "Rates",
    "The global discount rate: expected short rates over a decade plus a term premium.",
    { concept: "bond-yields", proxies: ["DGS10"] }),
  n("yield_curve", "Yield Curve (10y − 2y)", "rate", "Rates",
    "The spread between long and short yields. Inversion has preceded most post-war US recessions, with long and variable lags.",
    { concept: "yield-curve", proxies: ["T10Y2Y"] }),
  n("term_premium", "Term Premium", "rate", "Rates",
    "The extra yield demanded for holding duration rather than rolling bills. Estimated, never observed.",
    { concept: "term-premium" }),
  n("credit_spreads", "Credit Spreads", "rate", "Rates",
    "What corporate borrowers pay above governments. The cleanest real-time read on perceived default risk.",
    { concept: "credit-spreads", proxies: ["BAMLH0A0HYM2"] }),
  n("mortgage_rate", "Mortgage Rates", "rate", "Rates",
    "Priced off the 10-year plus a spread that widens when mortgage-backed securities are hard to hedge.",
    { proxies: ["MORTGAGE30US"] }),
  n("financial_conditions", "Financial Conditions", "rate", "Rates",
    "A composite of rates, spreads, equity levels and the dollar — how easy it is to raise and service money.",
    { concept: "financial-conditions" }),
  n("bank_lending", "Bank Lending Standards", "rate", "Rates",
    "Whether banks are willing to lend. Surveys of loan officers lead credit growth by quarters.",
    { concept: "credit-channel" }),

  /* --- Inflation --------------------------------------------------------- */
  n("headline_inflation", "Headline Inflation", "inflation", "Prices",
    "The full consumer basket including food and energy — what households actually experience.",
    { concept: "inflation", proxies: ["CPIAUCSL"] }),
  n("core_inflation", "Core Inflation", "inflation", "Prices",
    "Headline stripped of food and energy, used because it predicts future headline better than headline does.",
    { concept: "core-inflation", proxies: ["CPILFESL", "PCEPILFE"] }),
  n("services_inflation", "Services Inflation", "inflation", "Prices",
    "The stickier half of the basket. Largely wages, and therefore slow to turn.",
    { concept: "sticky-inflation" }),
  n("shelter_inflation", "Shelter Inflation", "inflation", "Prices",
    "About a third of US CPI. Measured with a lag of roughly a year against market rents.",
    { concept: "shelter-cpi" }),
  n("goods_inflation", "Goods Inflation", "inflation", "Prices",
    "The tradable, import-sensitive half of the basket. Moves with the dollar, freight and tariffs."),
  n("inflation_expectations", "Inflation Expectations", "inflation", "Prices",
    "What households, firms and markets think inflation will be. Central banks treat de-anchoring as the true failure state.",
    { concept: "inflation-expectations", proxies: ["T5YIE", "MICH"] }),
  n("wage_growth", "Wage Growth", "inflation", "Prices",
    "Compensation per hour. Inflationary only to the extent it outruns productivity.",
    { concept: "wage-price", proxies: ["CES0500000003", "ECIALLCIV"] }),
  n("unit_labor_costs", "Unit Labour Costs", "inflation", "Prices",
    "Wage growth minus productivity growth — the cost pressure firms must either absorb or pass on."),
  n("productivity", "Productivity Growth", "macro", "Prices",
    "Output per hour. The only source of non-inflationary wage gains, and the hardest number to forecast.",
    { concept: "productivity" }),

  /* --- Activity and labour ---------------------------------------------- */
  n("gdp", "GDP Growth", "macro", "Activity",
    "The value of everything produced. Backward-looking, heavily revised, still the reference series.",
    { concept: "gdp", proxies: ["GDPC1"] }),
  n("consumer_spending", "Consumer Spending", "macro", "Activity",
    "Roughly two-thirds of US GDP. Its resilience or fragility usually decides recessions.",
    { proxies: ["PCE"] }),
  n("business_investment", "Business Investment", "macro", "Activity",
    "Capital expenditure by firms — volatile, rate-sensitive, and the main channel from policy to output.",
    { concept: "capex-cycle" }),
  n("housing_activity", "Housing Activity", "macro", "Activity",
    "Starts, permits and existing-home sales. The most rate-sensitive sector in the economy.",
    { proxies: ["HOUST", "PERMIT"] }),
  n("home_prices", "Home Prices", "macro", "Activity",
    "The largest household asset. Feeds shelter inflation with a long lag and consumption via wealth effects.",
    { proxies: ["CSUSHPINSA"] }),
  n("manufacturing", "Manufacturing Output", "macro", "Activity",
    "Small share of employment, outsized share of the business cycle's amplitude.",
    { proxies: ["INDPRO", "NAPM"] }),
  n("services_activity", "Services Activity", "macro", "Activity",
    "The larger and steadier side of a modern economy. Turns later and less violently than manufacturing."),
  n("unemployment", "Unemployment Rate", "macro", "Labour",
    "The share of the labour force actively seeking work. Lagging, but politically decisive.",
    { concept: "unemployment", proxies: ["UNRATE"] }),
  n("payrolls", "Payroll Growth", "macro", "Labour",
    "Net jobs added each month. Timely, noisy and revised — read the trend, not the print.",
    { proxies: ["PAYEMS"] }),
  n("job_openings", "Job Openings", "macro", "Labour",
    "Unfilled positions. Falling openings without rising unemployment is the benign cooling path.",
    { concept: "beveridge-curve", proxies: ["JTSJOL"] }),
  n("labor_supply", "Labour Supply", "structural", "Labour",
    "Participation plus immigration plus demographics. Sets how fast the economy can grow without inflation."),
  n("consumer_confidence", "Consumer Confidence", "macro", "Activity",
    "Sentiment surveys. Weakly predictive of spending, strongly predictive of politics.",
    { proxies: ["UMCSENT"] }),
  n("household_debt", "Household Debt Service", "macro", "Activity",
    "Debt payments as a share of income. Determines how hard rate rises bite.",
    { proxies: ["TDSP"] }),
  n("delinquencies", "Consumer Delinquencies", "macro", "Activity",
    "Missed payments on cards, autos and mortgages. An early read on household stress."),
  n("corporate_profits", "Corporate Profits", "macro", "Activity",
    "Aggregate earnings — the bridge between the economy and the equity market.",
    { concept: "earnings" }),

  /* --- Fiscal and policy ------------------------------------------------- */
  n("fiscal_deficit", "Fiscal Deficit", "policy", "Fiscal",
    "Government spending minus revenue. Adds to demand today and to debt issuance tomorrow.",
    { concept: "fiscal-policy" }),
  n("debt_issuance", "Treasury Issuance", "policy", "Fiscal",
    "The supply of government bonds. Composition between bills and coupons matters as much as the total."),
  n("tariffs", "Tariffs & Trade Barriers", "policy", "Fiscal",
    "Taxes on imports. Raise domestic goods prices, invite retaliation, redirect supply chains.",
    { concept: "tariffs" }),
  n("industrial_policy", "Industrial Policy", "policy", "Fiscal",
    "State subsidy and direction of specific industries — semiconductors, batteries, defence, energy.",
    { concept: "industrial-policy" }),
  n("regulation_ai", "AI Regulation", "policy", "Fiscal",
    "Rules on model training, deployment, liability and compute. Currently divergent across jurisdictions."),
  n("export_controls", "Export Controls", "policy", "Fiscal",
    "Restrictions on selling advanced technology abroad — chiefly semiconductors and the tools that make them.",
    { concept: "export-controls" }),
  n("defense_spending", "Defence Spending", "policy", "Fiscal",
    "Government military procurement and R&D. Slow to start, slow to stop."),

  /* --- External and currency -------------------------------------------- */
  n("usd", "US Dollar", "fx", "External",
    "The world's funding and invoicing currency. Its level is a global financial condition, not just a price.",
    { concept: "dollar", proxies: ["DTWEXBGS"] }),
  n("usdcad", "USD/CAD", "fx", "External",
    "Driven by rate differentials and oil. A weaker loonie imports inflation into Canada.",
    { proxies: ["FXUSDCAD"] }),
  n("eurusd", "EUR/USD", "fx", "External",
    "The most-traded pair; largely a rate-differential and energy-terms-of-trade story.",
    { proxies: ["EXR.D.USD.EUR.SP00.A"] }),
  n("global_growth", "Global Growth", "macro", "External",
    "World output. Determines external demand for every exporting economy."),
  n("china_growth", "China Growth", "macro", "External",
    "The marginal buyer of most industrial commodities and a major source of manufactured goods disinflation."),
  n("trade_flows", "Trade Volumes", "macro", "External",
    "Physical goods crossing borders. Sensitive to tariffs, freight costs and inventory cycles."),
  n("em_stress", "Emerging Market Stress", "risk", "External",
    "Dollar-funded borrowers face rising real burdens when the dollar rises and US rates climb."),

  /* --- Commodities ------------------------------------------------------- */
  n("oil", "Crude Oil", "commodity", "Commodities",
    "The single most macro-consequential price: an input to nearly everything and a transfer between producers and consumers.",
    { concept: "oil-shock", proxies: ["DCOILWTICO"] }),
  n("natgas", "Natural Gas", "commodity", "Commodities",
    "Regional, not global — pipelines and LNG terminals set the price, and it is the marginal power fuel in much of the world.",
    { proxies: ["DHHNGSP"] }),
  n("gasoline", "Gasoline", "commodity", "Commodities",
    "The most politically salient price in the United States, and a direct line into headline inflation."),
  n("electricity_price", "Electricity Prices", "commodity", "Commodities",
    "Set by the marginal generator. Rising load with slow supply additions raises the clearing price."),
  n("gold", "Gold", "commodity", "Commodities",
    "A non-yielding asset: rises when real rates fall, when the dollar weakens, and when institutions are distrusted.",
    { concept: "gold" }),
  n("copper", "Copper", "commodity", "Commodities",
    "The metal of electrification. Demand tracks construction, grid and vehicles; supply takes a decade to add.",
    { concept: "copper" }),
  n("uranium", "Uranium", "commodity", "Commodities",
    "Fuel for existing reactors and any nuclear build-out. Long-term contracted, supply concentrated in few countries."),
  n("lithium", "Lithium", "commodity", "Commodities",
    "Battery feedstock. Notoriously cyclical: high prices summon supply that then crushes the price."),
  n("rare_earths", "Rare Earths", "commodity", "Commodities",
    "Not geologically rare, but processing is concentrated — which makes them a policy lever, not just an input."),
  n("agriculture", "Agricultural Commodities", "commodity", "Commodities",
    "Grains and oilseeds. Weather, energy (via fertiliser and diesel) and export policy set the price."),
  n("freight", "Freight Rates", "commodity", "Commodities",
    "The cost of moving goods. Spikes when routes close or capacity is tight, and passes into goods prices."),

  /* --- Markets ----------------------------------------------------------- */
  n("sp500", "S&P 500", "market", "Markets",
    "Large-cap US equities — now heavily weighted toward a handful of technology franchises.",
    { proxies: ["^SPX"] }),
  n("nasdaq", "Nasdaq 100", "market", "Markets",
    "Long-duration growth equity. The most sensitive major index to real rates.",
    { proxies: ["^NDX"] }),
  n("russell2000", "Russell 2000", "market", "Markets",
    "Small caps: more domestic, more leveraged, more floating-rate debt, more cyclical.",
    { proxies: ["^RUT"] }),
  n("tsx", "S&P/TSX Composite", "market", "Markets",
    "Canada's index — structurally heavy in financials, energy and materials.",
    { proxies: ["^SPTSX"] }),
  n("equity_valuation", "Equity Valuations", "market", "Markets",
    "What investors pay per dollar of earnings. Mathematically a function of rates, growth and risk appetite.",
    { concept: "valuation" }),
  n("earnings_growth", "Earnings Growth", "market", "Markets",
    "The other half of equity returns. Revisions matter more to price than levels.",
    { concept: "earnings" }),
  n("volatility", "Equity Volatility", "market", "Markets",
    "The price of insurance against equity moves. Rises with uncertainty and with leverage unwinds.",
    { concept: "volatility", proxies: ["VIXCLS"] }),
  n("risk_appetite", "Risk Appetite", "market", "Markets",
    "The market's collective willingness to hold uncertain cash flows. Reflexive: it moves prices, prices move it."),
  n("ipo_ma", "IPO & M&A Activity", "market", "Markets",
    "Corporate issuance and dealmaking. A function of financing costs, valuation and regulatory posture."),
  n("venture_funding", "Venture Funding", "market", "Markets",
    "Private risk capital. Leads public-market technology cycles by roughly two to four years."),
  n("bitcoin", "Bitcoin", "market", "Markets",
    "Traded predominantly as a high-beta liquidity asset, whatever the monetary thesis says."),

  /* --- Sectors ----------------------------------------------------------- */
  n("semis", "Semiconductors", "sector", "Sectors",
    "The bottleneck industry of the digital economy: extreme capital intensity, extreme cyclicality.",
    { proxies: ["SOX"] }),
  n("software", "Software", "sector", "Sectors",
    "High gross margin, subscription revenue, long-duration cash flows — hence rate-sensitive valuations."),
  n("banks", "Banks", "sector", "Sectors",
    "Earn a spread between funding and lending; carry duration and credit risk on both sides of the balance sheet."),
  n("insurers", "Insurers", "sector", "Sectors",
    "Float invested largely in bonds. Higher yields raise investment income; claims inflation raises costs."),
  n("energy_sector", "Energy Producers", "sector", "Sectors",
    "Cash flow moves nearly one-for-one with commodity prices; capital discipline decides whether that reaches shareholders."),
  n("utilities", "Utilities", "sector", "Sectors",
    "Regulated returns on invested capital. Bond-like, until load growth turns them into growth companies."),
  n("miners", "Mining", "sector", "Sectors",
    "Operational leverage to metal prices, with a decade of lead time between price signal and new supply."),
  n("industrials", "Industrials", "sector", "Sectors",
    "Capital goods and services. Order books lead revenue by several quarters."),
  n("aerospace_defense", "Aerospace & Defence", "sector", "Sectors",
    "Multi-year government contracts. Revenue follows budgets, which follow threat perception with a lag."),
  n("transports", "Transport & Logistics", "sector", "Sectors",
    "Rails, trucking, shipping and air freight. Volume follows trade; margin follows fuel and capacity."),
  n("airlines", "Airlines", "sector", "Sectors",
    "Fuel is the largest variable cost and demand is highly income-elastic — a double-levered cyclical."),
  n("homebuilders", "Homebuilders", "sector", "Sectors",
    "Sell a rate-financed product. Volumes track mortgage affordability almost mechanically."),
  n("retail", "Retail", "sector", "Sectors",
    "Thin margins on discretionary volume. Real income growth, not nominal spending, is the variable that matters."),
  n("autos", "Automotive", "sector", "Sectors",
    "Credit-financed durable goods in the middle of a contested technology transition."),
  n("staples", "Consumer Staples", "sector", "Sectors",
    "Defensive volumes with pricing power that works in inflation and reverses in disinflation."),
  n("healthcare", "Healthcare", "sector", "Sectors",
    "Demand is demographic and non-cyclical; policy and reimbursement are the real risks."),
  n("biotech", "Biotech", "sector", "Sectors",
    "Pre-revenue, cash-burning, long-duration. Among the most rate-sensitive equity groups."),
  n("reits", "Real Estate (REITs)", "sector", "Sectors",
    "Levered property with rents on one side and financing costs on the other."),
  n("data_center_reits", "Data Centre Real Estate", "industry", "AI Chain",
    "Shells, power interconnects and cooling let to compute tenants — the physical layer of AI capacity."),

  /* --- The AI / compute / power chain ----------------------------------- */
  n("ai_capability", "AI Model Capability", "tech", "AI Chain",
    "What frontier systems can reliably do. The upstream driver of every other node in this chain.",
    { concept: "scaling-laws" }),
  n("ai_capex", "AI Capital Expenditure", "tech", "AI Chain",
    "Spending by hyperscalers, labs and enterprises on compute capacity. Currently the largest private capex cycle in technology."),
  n("ai_adoption", "Enterprise AI Adoption", "tech", "AI Chain",
    "Deployment into real workflows. The gap between capability and adoption is where most of the economic value is decided."),
  n("compute_demand", "Compute Demand", "tech", "AI Chain",
    "Aggregate demand for training and inference. Inference scales with usage; training scales with ambition."),
  n("accelerators", "AI Accelerators", "industry", "AI Chain",
    "GPUs and custom silicon. Designed by a few firms, fabricated by fewer."),
  n("foundry", "Leading-Edge Foundry", "industry", "AI Chain",
    "Contract manufacturing at the most advanced nodes — the tightest bottleneck in the chain."),
  n("advanced_packaging", "Advanced Packaging", "industry", "AI Chain",
    "Stacking and interconnecting die. Repeatedly the binding constraint on accelerator output."),
  n("hbm", "High-Bandwidth Memory", "industry", "AI Chain",
    "Stacked DRAM beside the processor. Capacity is contracted years ahead and hard to expand quickly."),
  n("semicap", "Semiconductor Equipment", "industry", "AI Chain",
    "The tools that build fabs. Revenue leads fab output by roughly a year and is a chokepoint for policy."),
  n("data_center_buildout", "Data Centre Build-Out", "industry", "AI Chain",
    "Land, shells, power and cooling. Constrained less by capital than by grid interconnection queues."),
  n("dc_cooling", "Thermal Management", "industry", "AI Chain",
    "Rack density has outgrown air cooling, forcing liquid systems and new equipment vendors."),
  n("power_demand", "Electricity Demand", "industry", "AI Chain",
    "After two decades of flat load in developed markets, data centres and electrification have restarted growth."),
  n("grid_capacity", "Grid Capacity", "industry", "AI Chain",
    "Transmission, substations and interconnection. Permitting timelines, not technology, are the constraint."),
  n("grid_equipment", "Grid Equipment", "industry", "AI Chain",
    "Transformers, switchgear, cable. Lead times stretched from months to years across the last cycle."),
  n("gas_turbines", "Gas Generation", "industry", "AI Chain",
    "Dispatchable capacity that can be built on a several-year horizon — the default answer to urgent load."),
  n("nuclear_power", "Nuclear Power", "industry", "AI Chain",
    "Firm, carbon-free baseload. Existing plants are being revalued; new large builds remain slow and expensive."),
  n("smr", "Small Modular Reactors", "tech", "AI Chain",
    "Factory-built reactors promising shorter schedules. Regulatory precedent and a first commercial fleet are still pending."),
  n("renewables", "Renewables", "industry", "AI Chain",
    "Cheapest marginal energy in many markets, but intermittent — which pushes value toward firming and storage."),
  n("storage", "Grid Storage", "industry", "AI Chain",
    "Batteries that shift renewable output in time. The economics improve as intraday price spreads widen."),
  n("networking", "Networking & Optics", "industry", "AI Chain",
    "Moving data between accelerators. Cluster scale makes interconnect a first-order performance constraint."),
  n("cloud_capex", "Cloud Capital Spending", "industry", "AI Chain",
    "Hyperscaler infrastructure budgets — the largest single source of demand in the chain."),
  n("labor_automation", "Task Automation", "structural", "AI Chain",
    "Substitution of software for cognitive labour. Measurable first in support, coding, drafting and analysis."),
  n("robotics", "Robotics", "tech", "Frontier",
    "Physical automation. Advancing where perception improved fastest; dexterity remains the hard problem."),
  n("autonomous_vehicles", "Autonomous Vehicles", "tech", "Frontier",
    "Commercially live in geofenced areas; the open question is cost per mile, not feasibility."),
  n("quantum", "Quantum Computing", "tech", "Frontier",
    "Error correction is improving; commercially decisive applications remain unproven."),
  n("space", "Space Access", "tech", "Frontier",
    "Falling launch cost has changed what is economic in orbit — chiefly communications and imaging."),
  n("cybersecurity", "Cybersecurity", "tech", "Frontier",
    "Spending is defensive and non-discretionary, and rises with both attack sophistication and digitisation."),
  n("biotech_platform", "Computational Biology", "tech", "Frontier",
    "Machine learning applied to protein structure, target discovery and trial design."),

  /* --- Structural -------------------------------------------------------- */
  n("aging", "Population Ageing", "structural", "Structural",
    "The most predictable force in economics: fewer workers per retiree across most large economies."),
  n("immigration", "Immigration", "structural", "Structural",
    "The main short-run policy lever on labour supply — and increasingly a political constraint."),
  n("housing_supply", "Housing Supply", "structural", "Structural",
    "Constrained by land use and permitting more than by construction capacity."),
  n("energy_transition", "Energy Transition", "structural", "Structural",
    "The multi-decade capital rotation toward electrification, with commodity and grid consequences."),
  n("electrification", "Electrification", "structural", "Structural",
    "Moving transport, heat and industry onto the grid — the demand-side half of the transition."),
  n("reshoring", "Reshoring & Friend-Shoring", "structural", "Structural",
    "Relocating production for resilience rather than cost. Raises capex and, at the margin, prices."),
  n("supply_chain", "Supply Chain Resilience", "structural", "Structural",
    "Inventory buffers and dual sourcing. Cheap insurance in good years, decisive in bad ones."),
  n("water_stress", "Water Stress", "structural", "Structural",
    "A binding constraint on agriculture, semiconductor fabrication and thermal generation alike."),
  n("climate_adaptation", "Climate Adaptation", "structural", "Structural",
    "Spending to withstand physical risk: insurance, infrastructure hardening, resilient construction."),

  /* --- Geopolitical risk ------------------------------------------------- */
  n("geopolitical_risk", "Geopolitical Risk", "risk", "Geopolitics",
    "Aggregate conflict and coercion risk. Raises risk premia and reroutes trade before it changes output."),
  n("taiwan_risk", "Taiwan Strait Risk", "risk", "Geopolitics",
    "Concentrated leading-edge semiconductor manufacturing makes this the highest-consequence single node in global supply."),
  n("middle_east_risk", "Middle East Instability", "risk", "Geopolitics",
    "Matters to markets mainly through oil supply, shipping routes and insurance costs."),
  n("russia_ukraine", "Russia–Ukraine War", "risk", "Geopolitics",
    "Reshaped European energy sourcing, defence budgets and grain trade."),
  n("trade_fragmentation", "Trade Fragmentation", "risk", "Geopolitics",
    "Blocs replacing a single trading system. Raises costs, duplicates capacity, and slows diffusion."),
  n("sanctions", "Sanctions Regimes", "risk", "Geopolitics",
    "Financial and technological restriction as statecraft. Effects compound slowly and are hard to reverse."),
  n("election_risk", "Electoral & Policy Risk", "risk", "Geopolitics",
    "Scheduled uncertainty. Markets price the distribution of policy, not the winner."),
  n("financial_instability", "Financial Instability", "risk", "Geopolitics",
    "Leverage meeting a repricing. Usually surfaces where funding is short and assets are long."),
];

export const NODE_BY_ID = new Map(NODES.map((node) => [node.id, node]));

export const GROUPS = [...new Set(NODES.map((node) => node.group))];

export const KIND_LABEL = {
  macro: "Macro", rate: "Rates", inflation: "Inflation", policy: "Policy",
  commodity: "Commodity", fx: "Currency", market: "Market", sector: "Sector",
  industry: "Industry", tech: "Technology", structural: "Structural", risk: "Risk",
};
