/**
 * WORLD MODEL — EDGES
 *
 * Each edge is a claim about a transmission channel, not a claim about the
 * future. It carries:
 *
 *   sign        +1 same direction, −1 opposite
 *   strength    0–1, how much of an upstream move typically transmits
 *   lag         months until the effect is normally visible
 *   confidence  high      textbook mechanism with consistent historical support
 *               moderate  well-established but state-dependent
 *               low       plausible, contested, or thin evidence
 *   why         the mechanism, in one sentence — the reason this edge exists
 *
 * These are analytical judgements, and the interface labels them as such. They
 * are not measured coefficients, and nothing here should be read as a forecast.
 * The propagation engine damps every hop precisely because the uncertainty of a
 * chain compounds far faster than its plausibility.
 */

const e = (from, to, sign, strength, lag, confidence, why) =>
  ({ from, to, sign, strength, lag, confidence, why });

export const EDGES = [
  /* === Monetary transmission ============================================= */
  e("policy_rate", "ust2y", 1, 0.9, 0, "high",
    "Two-year yields are largely an average of expected policy rates, so they move with the policy path."),
  e("policy_rate", "ust10y", 1, 0.45, 0, "high",
    "Long yields inherit the expected policy path, but term premium and growth expectations dilute the pass-through."),
  e("ust10y", "yield_curve", 1, 0.8, 0, "high",
    "The curve is defined as the long yield minus the short one."),
  e("ust2y", "yield_curve", -1, 0.8, 0, "high",
    "A rising short yield compresses the spread by construction."),
  e("policy_rate", "real_rate", 1, 0.8, 1, "high",
    "With expectations anchored, a nominal rate rise raises the real rate roughly one-for-one."),
  e("inflation_expectations", "real_rate", -1, 0.75, 0, "high",
    "The real rate is the nominal rate minus expected inflation."),
  e("balance_sheet", "term_premium", -1, 0.5, 3, "moderate",
    "Central bank duration purchases remove interest-rate risk from private portfolios and compress the premium."),
  e("term_premium", "ust10y", 1, 0.9, 0, "high",
    "Term premium is an additive component of the long yield."),
  e("debt_issuance", "term_premium", 1, 0.4, 2, "moderate",
    "More duration for private buyers to absorb raises the compensation they demand — clearest when issuance is skewed to coupons."),
  e("fiscal_deficit", "debt_issuance", 1, 0.9, 2, "high",
    "Deficits are funded by selling bonds."),
  e("policy_rate", "mortgage_rate", 1, 0.55, 1, "high",
    "Mortgages price off the long end plus a spread, so they follow policy only partially."),
  e("ust10y", "mortgage_rate", 1, 0.85, 0, "high",
    "Thirty-year mortgages are hedged against long Treasuries; the spread moves with volatility."),
  e("policy_rate", "financial_conditions", -1, 0.7, 0, "high",
    "Higher policy rates tighten conditions across rates, credit and the dollar simultaneously."),
  e("credit_spreads", "financial_conditions", -1, 0.7, 0, "high",
    "Wider spreads mean higher marginal borrowing costs for the real economy."),
  e("sp500", "financial_conditions", 1, 0.4, 0, "moderate",
    "Equity levels enter conditions indices via wealth effects and the cost of equity capital."),
  e("usd", "financial_conditions", -1, 0.35, 0, "moderate",
    "A stronger dollar tightens conditions for dollar borrowers worldwide."),
  e("policy_rate", "bank_lending", -1, 0.55, 3, "high",
    "Higher rates tighten loan officer standards as expected loss and funding cost both rise."),
  e("bank_lending", "business_investment", -1, 0.5, 6, "high",
    "Small and mid-sized firms fund capex through banks, not bond markets."),
  e("bank_lending", "consumer_spending", -1, 0.35, 6, "moderate",
    "Tighter card and auto credit constrains the marginal consumer."),

  /* === Rates into the real economy ====================================== */
  e("mortgage_rate", "housing_activity", -1, 0.8, 3, "high",
    "Buyers finance a monthly payment, not a price; higher rates price out marginal buyers immediately."),
  e("mortgage_rate", "home_prices", -1, 0.45, 9, "moderate",
    "Prices adjust slower than volumes because sellers withdraw rather than cut — the lock-in effect."),
  e("housing_activity", "homebuilders", 1, 0.85, 0, "high",
    "Builder revenue is starts times price."),
  e("housing_activity", "gdp", 1, 0.25, 3, "high",
    "Residential investment is a small share of GDP but an outsized share of its cyclical variance."),
  e("home_prices", "shelter_inflation", 1, 0.35, 12, "high",
    "Owners' equivalent rent follows market rents, which follow prices, with roughly a year's measurement lag."),
  e("home_prices", "consumer_spending", 1, 0.25, 6, "moderate",
    "Housing wealth effects are real but smaller than headlines imply, and work mainly through refinancing."),
  e("real_rate", "business_investment", -1, 0.6, 6, "high",
    "Projects are approved against a hurdle rate; a higher real rate shrinks the set that clears it."),
  e("real_rate", "equity_valuation", -1, 0.7, 0, "high",
    "Valuation is the present value of future cash flows; the discount rate is in the denominator."),
  e("real_rate", "gold", -1, 0.6, 0, "high",
    "Gold pays no coupon, so its opportunity cost is the real yield on bonds."),
  e("real_rate", "biotech", -1, 0.6, 1, "moderate",
    "Pre-revenue cash flows sit far in the future, making them maximally sensitive to discounting."),
  e("real_rate", "reits", -1, 0.55, 3, "high",
    "Property is levered and valued off cap rates that track real yields."),
  e("household_debt", "consumer_spending", -1, 0.4, 3, "high",
    "Debt service is a prior claim on income."),
  e("policy_rate", "household_debt", 1, 0.35, 6, "moderate",
    "The pass-through depends on fixed-rate share: fast in Canada, Australia and the UK, slow in the US."),
  e("unemployment", "delinquencies", 1, 0.6, 3, "high",
    "Job loss is the dominant cause of missed consumer payments."),
  e("delinquencies", "bank_lending", -1, 0.45, 3, "high",
    "Realised losses tighten underwriting."),
  e("business_investment", "gdp", 1, 0.35, 3, "high",
    "Capex is a direct GDP component and a driver of the capital goods cycle."),
  e("consumer_spending", "gdp", 1, 0.65, 0, "high",
    "Consumption is roughly two-thirds of US output."),
  e("gdp", "corporate_profits", 1, 0.6, 3, "high",
    "Aggregate profits are the residual of nominal output after wages and interest."),
  e("corporate_profits", "earnings_growth", 1, 0.8, 3, "high",
    "Index earnings are a levered subset of national profits."),
  e("earnings_growth", "sp500", 1, 0.6, 0, "high",
    "Price is earnings times multiple; revisions move price faster than levels."),
  e("equity_valuation", "sp500", 1, 0.7, 0, "high",
    "The multiple is the other half of the price identity."),

  /* === Labour and inflation ============================================= */
  e("gdp", "payrolls", 1, 0.6, 3, "high",
    "Firms hire against expected demand, with a lag and some labour hoarding."),
  e("payrolls", "unemployment", -1, 0.65, 1, "high",
    "Job creation above labour force growth lowers the rate."),
  e("labor_supply", "unemployment", 1, 0.4, 3, "moderate",
    "A larger labour force raises measured unemployment before it lowers wage pressure."),
  e("immigration", "labor_supply", 1, 0.7, 6, "high",
    "Immigration is the fastest-moving component of labour force growth."),
  e("aging", "labor_supply", -1, 0.5, 24, "high",
    "Retirements subtract from participation with near-total predictability."),
  e("job_openings", "wage_growth", 1, 0.5, 6, "high",
    "Vacancies per unemployed worker is the tightest available proxy for bargaining power."),
  e("unemployment", "wage_growth", -1, 0.55, 6, "high",
    "Slack reduces the wage a worker can command — non-linearly, steepening as slack disappears."),
  e("wage_growth", "unit_labor_costs", 1, 0.85, 1, "high",
    "Unit labour cost is compensation growth net of productivity."),
  e("productivity", "unit_labor_costs", -1, 0.8, 3, "high",
    "Output per hour offsets wage growth one-for-one in cost terms."),
  e("unit_labor_costs", "services_inflation", 1, 0.6, 6, "high",
    "Services are mostly labour, so labour cost is the dominant input price."),
  e("services_inflation", "core_inflation", 1, 0.65, 0, "high",
    "Services are the larger and stickier share of the core basket."),
  e("shelter_inflation", "core_inflation", 1, 0.4, 0, "high",
    "Shelter is roughly a third of US CPI and about 40% of core."),
  e("goods_inflation", "core_inflation", 1, 0.3, 0, "high",
    "Core goods is the smaller, more volatile and more import-sensitive component."),
  e("core_inflation", "headline_inflation", 1, 0.7, 0, "high",
    "Core is most of the basket; food and energy add the volatility."),
  e("oil", "gasoline", 1, 0.85, 0, "high",
    "Crude is the dominant input to refined product prices, with refining margin on top."),
  e("gasoline", "headline_inflation", 1, 0.35, 0, "high",
    "Energy enters headline CPI directly and immediately."),
  e("headline_inflation", "inflation_expectations", 1, 0.45, 3, "high",
    "Household expectations track visible prices — fuel and groceries above all."),
  e("inflation_expectations", "wage_growth", 1, 0.4, 6, "moderate",
    "Expected inflation enters wage bargaining; the strength of this link is the central question in every inflation episode."),
  e("core_inflation", "policy_rate", 1, 0.7, 3, "high",
    "The reaction function: persistent core inflation above target pulls policy tighter."),
  e("unemployment", "policy_rate", -1, 0.5, 3, "high",
    "The employment half of the dual mandate pulls in the opposite direction."),
  e("inflation_expectations", "policy_rate", 1, 0.5, 3, "high",
    "De-anchoring expectations is the outcome central banks will accept a recession to prevent."),
  e("usd", "goods_inflation", -1, 0.35, 6, "high",
    "A stronger dollar lowers the local-currency cost of imports."),
  e("freight", "goods_inflation", 1, 0.25, 4, "moderate",
    "Shipping is a small share of landed cost except when rates spike by multiples."),
  e("tariffs", "goods_inflation", 1, 0.5, 3, "high",
    "A tariff is a tax on imports; incidence is split between exporter margin and domestic price."),
  e("productivity", "gdp", 1, 0.5, 12, "high",
    "Long-run growth is labour force growth plus productivity growth. There is no third term."),

  /* === Currency and external ============================================ */
  e("policy_rate", "usd", 1, 0.5, 0, "high",
    "Rate differentials drive carry, and carry drives flows — as long as risk appetite holds."),
  e("real_rate", "usd", 1, 0.45, 0, "high",
    "Real yield differentials matter more than nominal ones over the medium term."),
  e("risk_appetite", "usd", -1, 0.4, 0, "moderate",
    "The dollar is countercyclical: it strengthens when the world wants safety."),
  e("usd", "usdcad", 1, 0.7, 0, "high",
    "The pair is quoted in dollars, so broad dollar strength shows up directly."),
  e("oil", "usdcad", -1, 0.4, 0, "high",
    "Canada's terms of trade improve with crude, supporting the currency."),
  e("usd", "em_stress", 1, 0.55, 3, "high",
    "Emerging market borrowers owe dollars and earn local currency; the mismatch bites when the dollar rises."),
  e("usd", "oil", -1, 0.3, 0, "moderate",
    "Commodities are dollar-priced, so a stronger dollar mechanically weighs on the price — a correlation that breaks during supply shocks."),
  e("usd", "gold", -1, 0.45, 0, "high",
    "Same denomination effect, amplified by gold's role as a dollar alternative."),
  e("usd", "earnings_growth", -1, 0.25, 6, "high",
    "Roughly 40% of S&P 500 revenue is earned abroad and translated back into dollars."),
  e("china_growth", "copper", 1, 0.6, 3, "high",
    "China is the largest single source of refined copper demand, mostly via construction and grid."),
  e("china_growth", "global_growth", 1, 0.4, 3, "high",
    "China is a large share of world output growth at the margin."),
  e("china_growth", "goods_inflation", -1, 0.3, 6, "moderate",
    "Chinese manufacturing overcapacity exports disinflation in tradable goods."),
  e("global_growth", "trade_flows", 1, 0.7, 3, "high",
    "Trade volumes are a levered function of world output."),
  e("global_growth", "oil", 1, 0.5, 3, "high",
    "Oil demand is closely tied to industrial activity and mobility."),
  e("tariffs", "trade_flows", -1, 0.45, 6, "high",
    "Tariffs reduce and redirect trade rather than eliminate it."),
  e("tariffs", "reshoring", 1, 0.4, 24, "moderate",
    "Durable trade barriers change plant location decisions — but only once firms believe they are durable."),
  e("trade_fragmentation", "supply_chain", 1, 0.5, 12, "moderate",
    "Fragmentation forces duplicate inventory and second sourcing."),
  e("supply_chain", "goods_inflation", 1, 0.3, 6, "moderate",
    "Resilience is bought with working capital and duplicated capacity, both of which cost margin."),

  /* === Commodities ====================================================== */
  e("oil", "energy_sector", 1, 0.8, 0, "high",
    "Producer cash flow moves close to one-for-one with the realised price."),
  e("oil", "airlines", -1, 0.6, 1, "high",
    "Jet fuel is typically the largest or second-largest airline cost line."),
  e("oil", "transports", -1, 0.35, 1, "high",
    "Diesel is a direct operating cost, partly offset by fuel surcharges."),
  e("oil", "consumer_spending", -1, 0.3, 2, "high",
    "Fuel is a non-discretionary purchase, so higher prices crowd out discretionary spending."),
  e("oil", "agriculture", 1, 0.3, 6, "moderate",
    "Diesel and gas-derived fertiliser are major farm input costs."),
  e("natgas", "electricity_price", 1, 0.55, 1, "high",
    "Gas sets the marginal cost of generation in most hours in many markets."),
  e("natgas", "agriculture", 1, 0.35, 6, "high",
    "Nitrogen fertiliser is made from natural gas."),
  e("electricity_price", "utilities", 1, 0.25, 6, "moderate",
    "Regulated utilities pass fuel through; the earnings effect runs through rate base, not price."),
  e("copper", "miners", 1, 0.8, 0, "high",
    "Operational leverage: a fixed cost base against a moving price."),
  e("agriculture", "headline_inflation", 1, 0.2, 4, "high",
    "Food is a direct CPI component with a short pass-through to shelf prices."),
  e("middle_east_risk", "oil", 1, 0.45, 0, "high",
    "The region holds most of the world's spare production capacity and its critical chokepoints."),
  e("middle_east_risk", "freight", 1, 0.4, 1, "high",
    "Rerouting around threatened straits adds days at sea and multiplies war-risk insurance."),
  e("russia_ukraine", "natgas", 1, 0.35, 0, "moderate",
    "The war permanently rerouted European gas sourcing toward LNG, raising the marginal cost."),
  e("russia_ukraine", "agriculture", 1, 0.3, 3, "high",
    "The Black Sea is a major export corridor for wheat, corn and sunflower oil."),
  e("energy_transition", "copper", 1, 0.5, 24, "high",
    "Electrification is copper-intensive: motors, cabling, chargers and grid all consume it."),
  e("energy_transition", "lithium", 1, 0.55, 18, "moderate",
    "Battery demand drives lithium, though chemistry substitution is a persistent risk to the thesis."),
  e("nuclear_power", "uranium", 1, 0.6, 12, "high",
    "Reactor operation and restarts consume fuel that is contracted years ahead."),

  /* === The AI → compute → power chain ================================== */
  e("ai_capability", "ai_adoption", 1, 0.6, 12, "moderate",
    "Capability is necessary but not sufficient — deployment is gated by trust, integration and process change."),
  e("ai_capability", "ai_capex", 1, 0.7, 6, "high",
    "Each capability step has so far justified the next round of training investment."),
  e("ai_adoption", "compute_demand", 1, 0.7, 6, "high",
    "Inference scales with usage, and usage is adoption."),
  e("ai_capex", "compute_demand", 1, 0.8, 3, "high",
    "Training runs consume the capacity that capex builds."),
  e("cloud_capex", "ai_capex", 1, 0.8, 0, "high",
    "Hyperscalers are the largest buyers of AI infrastructure."),
  e("compute_demand", "accelerators", 1, 0.85, 3, "high",
    "Accelerators are the unit of compute supply."),
  e("accelerators", "foundry", 1, 0.8, 6, "high",
    "Accelerator designers are fabless; leading-edge wafer supply is the binding input."),
  e("accelerators", "advanced_packaging", 1, 0.85, 6, "high",
    "Packaging capacity has repeatedly, not occasionally, been the constraint on shipments."),
  e("accelerators", "hbm", 1, 0.85, 6, "high",
    "Memory bandwidth, not raw compute, limits large-model throughput."),
  e("foundry", "semicap", 1, 0.75, 12, "high",
    "Fab expansion is equipment purchases; tool orders lead wafer output by about a year."),
  e("advanced_packaging", "semicap", 1, 0.6, 9, "high",
    "Packaging capacity additions are also equipment purchases."),
  e("accelerators", "semis", 1, 0.7, 0, "high",
    "Accelerators are now the dominant swing factor in semiconductor industry revenue."),
  e("compute_demand", "data_center_buildout", 1, 0.8, 9, "high",
    "Chips need a building, power and cooling before they compute anything."),
  e("data_center_buildout", "data_center_reits", 1, 0.7, 6, "high",
    "Demand for shells and interconnection is the landlord's revenue."),
  e("data_center_buildout", "dc_cooling", 1, 0.75, 6, "high",
    "Rack density has passed what air can remove, forcing liquid cooling into new builds."),
  e("data_center_buildout", "power_demand", 1, 0.8, 9, "high",
    "A data centre is, physically, a very large and very steady electrical load."),
  e("data_center_buildout", "networking", 1, 0.7, 6, "high",
    "Cluster scale turns interconnect into a first-order design constraint."),
  e("data_center_buildout", "industrials", 1, 0.35, 9, "moderate",
    "Construction, electrical contracting and capital goods all capture part of the spend."),
  e("electrification", "power_demand", 1, 0.6, 24, "high",
    "Moving transport and heat onto the grid raises load structurally."),
  e("power_demand", "electricity_price", 1, 0.5, 12, "high",
    "Load growth against slow supply additions raises the clearing price."),
  e("power_demand", "grid_capacity", 1, 0.7, 18, "high",
    "New load must be interconnected, which is a transmission and substation problem."),
  e("grid_capacity", "grid_equipment", 1, 0.85, 12, "high",
    "Grid build-out is transformers, switchgear and cable — where lead times already stretched."),
  e("power_demand", "gas_turbines", 1, 0.55, 24, "high",
    "Dispatchable capacity buildable on a several-year horizon is the default answer to urgent load."),
  e("power_demand", "nuclear_power", 1, 0.45, 36, "moderate",
    "Firm, carbon-free baseload matches hyperscaler procurement goals, but new supply is slow."),
  e("power_demand", "renewables", 1, 0.5, 18, "high",
    "Renewables remain the fastest capacity to permit and build in most markets."),
  e("renewables", "storage", 1, 0.6, 18, "high",
    "Intermittent supply creates intraday price spreads, which are storage revenue."),
  e("power_demand", "utilities", 1, 0.5, 24, "moderate",
    "Load growth expands rate base — the mechanism by which a bond proxy becomes a growth business."),
  e("nuclear_power", "smr", 1, 0.4, 36, "low",
    "Renewed nuclear interest funds modular designs, but no commercial fleet yet validates the cost curve."),
  e("power_demand", "natgas", 1, 0.4, 18, "moderate",
    "Incremental gas generation raises fuel burn, competing with heating and LNG export demand."),
  e("grid_equipment", "copper", 1, 0.4, 12, "high",
    "Transformers and cable are copper-intensive."),
  e("ai_adoption", "labor_automation", 1, 0.6, 18, "moderate",
    "Substitution begins in text-heavy, verifiable tasks and spreads outward from there."),
  e("labor_automation", "productivity", 1, 0.45, 36, "low",
    "The mechanism is clear; the timing is not. Past general-purpose technologies took a decade to show up in the statistics."),
  e("labor_automation", "unemployment", 1, 0.2, 48, "low",
    "Historically automation reallocated labour rather than eliminating it — but the transition costs fell on identifiable people."),
  e("ai_adoption", "software", 1, 0.35, 12, "low",
    "Genuinely two-sided: AI expands what software can address while compressing the price of writing it."),
  e("ai_capability", "cybersecurity", 1, 0.4, 12, "moderate",
    "Cheaper offence forces higher defensive spend regardless of whether defence improves equally."),
  e("ai_capability", "biotech_platform", 1, 0.4, 24, "moderate",
    "Structure prediction and target discovery are already changing preclinical workflows."),
  e("ai_capability", "robotics", 1, 0.45, 24, "moderate",
    "Perception and planning improved first; manipulation remains the unsolved half."),
  e("regulation_ai", "ai_adoption", -1, 0.3, 12, "low",
    "Compliance cost slows deployment, though clear rules can also unlock regulated-sector adoption."),
  e("export_controls", "foundry", -1, 0.3, 12, "moderate",
    "Controls redirect and duplicate leading-edge capacity rather than reduce total demand for it."),
  e("export_controls", "semicap", -1, 0.35, 6, "high",
    "Equipment makers lose an addressable market directly and immediately."),
  e("taiwan_risk", "semis", -1, 0.7, 0, "high",
    "The overwhelming majority of leading-edge logic is fabricated on one island."),
  e("taiwan_risk", "geopolitical_risk", 1, 0.6, 0, "high",
    "It is the highest-consequence contingency in the current system."),
  e("industrial_policy", "foundry", 1, 0.4, 36, "moderate",
    "Subsidies shift where fabs are built; they change location faster than they change cost."),
  e("industrial_policy", "reshoring", 1, 0.45, 24, "moderate",
    "Capital grants and tax credits alter the arithmetic of domestic production."),

  /* === Markets and risk ================================================= */
  e("volatility", "risk_appetite", -1, 0.6, 0, "high",
    "Risk budgets are set in volatility units, so higher volatility forces mechanical de-risking."),
  e("risk_appetite", "credit_spreads", -1, 0.6, 0, "high",
    "Spreads are the price of bearing default risk."),
  e("risk_appetite", "sp500", 1, 0.5, 0, "high",
    "Multiple expansion and contraction is largely a risk-premium story."),
  e("risk_appetite", "venture_funding", 1, 0.5, 6, "high",
    "Private capital is the far end of the risk curve and moves last and hardest."),
  e("risk_appetite", "bitcoin", 1, 0.6, 0, "moderate",
    "Empirically it trades as a high-beta liquidity asset."),
  e("risk_appetite", "ipo_ma", 1, 0.5, 6, "high",
    "Issuance windows open when volatility is low and valuations are high."),
  e("credit_spreads", "ipo_ma", -1, 0.4, 3, "high",
    "Leveraged acquisition math depends directly on the cost of debt."),
  e("venture_funding", "ai_capex", 1, 0.3, 12, "moderate",
    "Private capital funds a meaningful share of frontier compute purchases."),
  e("financial_instability", "credit_spreads", 1, 0.7, 0, "high",
    "Stress shows up first in the price of credit."),
  e("financial_instability", "volatility", 1, 0.7, 0, "high",
    "Forced selling is what volatility measures."),
  e("financial_instability", "bank_lending", -1, 0.6, 3, "high",
    "Banks preserve capital when they fear losses, and lending is the first discretionary use of it."),
  e("geopolitical_risk", "volatility", 1, 0.35, 0, "moderate",
    "Markets price geopolitical risk in bursts and fade it quickly absent economic transmission."),
  e("geopolitical_risk", "defense_spending", 1, 0.5, 24, "high",
    "Threat perception raises budgets — slowly, and then persistently."),
  e("defense_spending", "aerospace_defense", 1, 0.75, 12, "high",
    "Contractor revenue is government procurement with a multi-year lag."),
  e("geopolitical_risk", "gold", 1, 0.3, 0, "moderate",
    "The safe-haven bid is real but short-lived unless real rates cooperate."),
  e("yield_curve", "banks", 1, 0.4, 6, "moderate",
    "Banks borrow short and lend long; a steeper curve widens net interest margin, so long as credit holds."),
  e("credit_spreads", "banks", -1, 0.5, 3, "high",
    "Wider spreads signal the credit losses that show up in provisions."),
  e("ust10y", "insurers", 1, 0.4, 6, "high",
    "Higher reinvestment yields raise investment income on the float."),
  e("policy_rate", "russell2000", -1, 0.45, 3, "high",
    "Small caps carry more floating-rate debt and refinance more often."),
  e("real_rate", "nasdaq", -1, 0.6, 0, "high",
    "Long-duration growth cash flows are the most discount-rate sensitive part of the equity market."),
  e("semis", "nasdaq", 1, 0.4, 0, "high",
    "Semiconductor weight in the index has risen with the AI cycle."),
  e("oil", "tsx", 1, 0.3, 0, "high",
    "Energy is a structurally large weight in the Canadian index."),
  e("banks", "tsx", 1, 0.35, 0, "high",
    "Financials are the largest sector weight in Canada."),
  e("sp500", "consumer_spending", 1, 0.2, 6, "moderate",
    "Equity wealth effects are concentrated in high-income households, who do a large share of discretionary spending."),
  e("consumer_confidence", "consumer_spending", 1, 0.2, 3, "low",
    "Sentiment has been a weak predictor of actual spending in recent cycles."),

  /* === Sector-level consequences ======================================== */
  e("consumer_spending", "retail", 1, 0.7, 1, "high",
    "Retail revenue is consumption, near-directly."),
  e("consumer_spending", "autos", 1, 0.5, 3, "high",
    "Vehicles are the largest discretionary durable purchase."),
  e("policy_rate", "autos", -1, 0.45, 3, "high",
    "Most vehicles are financed, so the monthly payment moves with rates."),
  e("unemployment", "consumer_spending", -1, 0.5, 1, "high",
    "Income lost to unemployment is spending lost."),
  e("gdp", "manufacturing", 1, 0.5, 3, "high",
    "Goods production amplifies the cycle through the inventory channel."),
  e("manufacturing", "industrials", 1, 0.6, 3, "high",
    "Capital goods orders follow industrial output."),
  e("trade_flows", "transports", 1, 0.6, 1, "high",
    "Freight volume is trade volume."),
  e("aging", "healthcare", 1, 0.6, 60, "high",
    "Healthcare consumption rises steeply with age, and the demographics are already determined."),
  e("aging", "labor_automation", 1, 0.3, 60, "moderate",
    "A shrinking workforce raises the return to substituting capital for labour."),
  e("water_stress", "agriculture", -1, 0.4, 12, "moderate",
    "Irrigation constraints bind yields in major producing regions."),
  e("water_stress", "foundry", -1, 0.2, 24, "low",
    "Fabrication is water-intensive, which shapes siting decisions more than output."),
  e("climate_adaptation", "insurers", -1, 0.35, 24, "moderate",
    "Rising insured losses force repricing and, in some markets, withdrawal of cover."),
  e("climate_adaptation", "industrials", 1, 0.3, 36, "low",
    "Hardening infrastructure is capital spending, but the timing depends on policy and loss experience."),
  e("housing_supply", "home_prices", -1, 0.5, 24, "high",
    "Supply is the only durable answer to housing costs; everything else moves demand."),
  e("immigration", "housing_activity", 1, 0.3, 12, "moderate",
    "Household formation drives absorption, especially in rental markets."),
  e("energy_transition", "energy_sector", -1, 0.2, 60, "low",
    "The long-run demand path is downward, but the near-term effect runs through underinvestment, which supports prices."),
  /* === Second currencies, orphan bridges, frontier tech ================= */
  e("policy_rate", "boc_rate", 1, 0.5, 3, "moderate",
    "The Bank of Canada sets policy independently, but a wide gap moves the currency enough to force partial convergence."),
  e("boc_rate", "usdcad", -1, 0.5, 0, "high",
    "A higher Canadian policy rate narrows the differential and supports the loonie."),
  e("boc_rate", "household_debt", 1, 0.55, 3, "high",
    "Canadian mortgages reset every few years, so policy reaches households far faster than in the United States."),
  e("core_inflation", "ecb_rate", 1, 0.6, 3, "high",
    "The ECB has a single mandate: price stability."),
  e("ecb_rate", "eurusd", 1, 0.5, 0, "high",
    "Euro-area rates relative to US rates are the dominant medium-term driver of the pair."),
  e("policy_rate", "eurusd", -1, 0.5, 0, "high",
    "The pair is the differential; a higher US rate pushes it down."),
  e("natgas", "eurusd", -1, 0.25, 3, "moderate",
    "Europe is a net energy importer, so an energy price shock worsens its terms of trade."),
  e("gdp", "services_activity", 1, 0.55, 1, "high",
    "Services are the majority of output in developed economies."),
  e("services_activity", "payrolls", 1, 0.5, 2, "high",
    "Services employ most workers, so hiring turns with services demand."),
  e("services_activity", "services_inflation", 1, 0.3, 6, "moderate",
    "Demand pressure in a labour-intensive sector shows up in prices with a lag."),
  e("export_controls", "rare_earths", 1, 0.4, 6, "moderate",
    "Restriction invites counter-restriction, and processing concentration makes these an obvious retaliation lever."),
  e("rare_earths", "aerospace_defense", -1, 0.3, 12, "moderate",
    "Magnets and specialty alloys sit deep in defence and motor supply chains."),
  e("rare_earths", "autos", -1, 0.25, 12, "moderate",
    "Permanent-magnet motors depend on rare earth elements."),
  e("energy_transition", "rare_earths", 1, 0.4, 24, "moderate",
    "Wind turbines and traction motors are the largest sources of incremental magnet demand."),
  e("headline_inflation", "staples", 1, 0.3, 3, "moderate",
    "Staples firms price to cost, so inflation supports nominal revenue — and disinflation reverses it."),
  e("consumer_spending", "staples", 1, 0.2, 3, "high",
    "Volumes are defensive: they fall less in downturns and grow less in expansions."),
  e("unemployment", "staples", 1, 0.15, 3, "moderate",
    "Staples outperform on a relative basis when the cycle turns down."),
  e("robotics", "autonomous_vehicles", 1, 0.4, 24, "moderate",
    "Shared perception, planning and safety-case machinery move the two together."),
  e("autonomous_vehicles", "transports", -1, 0.25, 60, "low",
    "If cost per mile falls materially, freight economics change — but the timeline has repeatedly slipped."),
  e("autonomous_vehicles", "autos", 1, 0.2, 48, "low",
    "Autonomy is a potential margin pool for manufacturers and a potential disintermediation of them."),
  e("ai_capability", "quantum", 1, 0.15, 60, "low",
    "Mostly a competition for the same scarce research talent and capital, with narrow scientific overlap."),
  e("quantum", "cybersecurity", 1, 0.3, 84, "low",
    "Cryptographically relevant quantum computing would force migration to post-quantum standards — long before it exists, it justifies spending."),
  e("space", "cybersecurity", 1, 0.15, 36, "low",
    "Orbital communications infrastructure expands the attack surface."),
  e("space", "defense_spending", 1, 0.3, 24, "moderate",
    "Space has become an explicit military domain in budget terms."),
  e("geopolitical_risk", "sanctions", 1, 0.5, 6, "high",
    "Sanctions are the standard instrument short of force."),
  e("sanctions", "trade_fragmentation", 1, 0.45, 12, "high",
    "Restriction accelerates the construction of parallel trading and payment systems."),
  e("sanctions", "oil", 1, 0.3, 3, "moderate",
    "Sanctions on producers reroute barrels and raise transaction costs more often than they remove supply."),
  e("sanctions", "gold", 1, 0.25, 12, "moderate",
    "Reserve managers holding sanctionable assets have a visible incentive to diversify."),
  e("election_risk", "volatility", 1, 0.25, 0, "moderate",
    "Scheduled uncertainty is priced in advance and released afterwards."),
  e("election_risk", "tariffs", 1, 0.3, 6, "moderate",
    "Trade policy is among the fastest levers a new executive can pull."),
  e("election_risk", "industrial_policy", 1, 0.3, 12, "moderate",
    "Subsidy programmes are durable but their scope is set by whoever writes the budget."),
  e("election_risk", "regulation_ai", 1, 0.3, 12, "low",
    "AI rulemaking is early enough that the direction still turns on who holds the pen."),
];


