#!/usr/bin/env bash
# Re-download the self-hosted font subsets from Google Fonts.
# Only needed if you change the families or weights in src/partials/layout.html.
# Fonts are committed to the repo, so a normal build never needs this.
set -euo pipefail
cd "$(dirname "$0")/.."

UA="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
URL="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,300;0,400;1,300;1,400&family=Jost:wght@200;300;400&display=swap"

mkdir -p assets/fonts
curl -sS -A "$UA" "$URL" -o /tmp/hv-gf.css
python3 - <<'PY'
import re, subprocess, os
css = open("/tmp/hv-gf.css").read()
KEEP = ("U+0000-00FF", "U+0100-02BA")   # latin + latin-ext
blocks = re.findall(r"/\*\s*([\w-]+)\s*\*/\s*(@font-face\s*\{.*?\})", css, re.S)
out = []
for label, block in blocks:
    ur = re.search(r"unicode-range:\s*([^;]+);", block)
    if not ur or not any(k in ur.group(1) for k in KEEP):
        continue
    fam = re.search(r"font-family:\s*'([^']+)'", block).group(1)
    style = re.search(r"font-style:\s*(\w+)", block).group(1)
    weight = re.search(r"font-weight:\s*(\d+)", block).group(1)
    url = re.search(r"url\((https://[^)]+)\)", block).group(1)
    slug = f"{fam.lower().replace(' ', '-')}-{weight}{'-italic' if style == 'italic' else ''}-{label}"
    subprocess.run(["curl", "-sS", "-o", f"assets/fonts/{slug}.woff2", url], check=True)
    out.append("@font-face {\n"
               f"  font-family: '{fam}';\n  font-style: {style};\n  font-weight: {weight};\n"
               "  font-display: swap;\n"
               f"  src: url('../fonts/{slug}.woff2') format('woff2');\n"
               f"  unicode-range: {ur.group(1).strip()};\n}}")
header = ("/* Self-hosted subsets of Cormorant Garamond and Jost (SIL Open Font License 1.1).\n"
          "   Generated by scripts/fetch-fonts.sh — latin + latin-ext only, woff2 only.\n"
          "   Self-hosting keeps the site free of third-party requests and render-blocking. */\n\n")
open("assets/css/fonts.css", "w").write(header + "\n".join(out) + "\n")
print(f"{len(out)} faces written")
PY
